### ISSUE TITLE
Add config.json invocation option

### ISSUE THREAD

**Issue by jasonmorton** [zkonduit/ezkl#138]
Currently, we construct the invocation config from either an environment variable or the command line flags (this config json is displayed just after the banner). As the command line gets more complex and tuned to a specific use case, these flags can be annoying to track. A better UX for some purposes would be an `ezkl fromconfig` command which takes one argument: a config.json file with exactly this configuration json. These config files can be tracked in version control in the same directory as the relevant network.onnx and input.json.

**Comment by danilowhk** [comment]
I can try this one

**Comment by jasonmorton** [comment]
Will use the existing functionality but document better
