### ISSUE TITLE
Make it easy to use RawBytes parameters

### ISSUE THREAD

**Issue by jasonmorton** [zkonduit/ezkl#139]
Previously we supported the "native" RawBytes params, which are in a format incompatible with public ceremonies, but are faster to load and save. Now we support loading public ceremony params, but have to pay the deserialization overhead which makes loading take longer. We could cache the RawBytes-format params after reading from a public setup, and reuse them on subsequent calls, or suggest running a conversion script. Ideally a solution would allow for the faster format, but not require additional steps.

**Comment by alexander-camuto** [comment]
Hopefully the ceremonies will be `RawBytes` by early next week and we can revert back from there.
