### ISSUE TITLE
`fix_verifier_sol.py` will not be called if ezkl is run from a different directory

### ISSUE THREAD

**Issue by JSeam2** [zkonduit/ezkl#150]
For the `.sol` file to be generated by `create-evm-verifier`, `fix_verifier_sol.py` must be present at the directory where `ezkl` is executed.

To replicate the issue, run `ezkl` out of the repo, and run the `prove` and `create-evm-verifier` function. An empty `.sol` file will be generated.

**Comment by alexander-camuto** [comment]
Hey @JSeam2 ! Thanks again for catching another issue. Attempted to resolve this in #151. Tested it locally and it seems to be working :). Let me know if this addresses your issue above.

**Comment by alexander-camuto** [comment]
I've done one better and moved all of the fix-verifier-sol functionality into rust in #152

**Comment by JSeam2** [comment]
@alexander-camuto it addresses the issue! #152 looks good!
