### ISSUE TITLE
Community Documentation

### ISSUE THREAD

**Issue by lancenonce** [zkonduit/ezkl#163]
Documentation for ezkl with community project examples. Should be:

- A separately existing site (not Rust docs) like a Gitbook
- Based off ezkl's README

**Comment by marciob** [comment]
I like the Gitbook idea, it's a good platform that many developers are familiar with. Some idea how it could be coordinated:

1. Someone from the team create a Gitbook account.
2. A kind of doc struct is defined to be used in the Gitbook (ex.: topics to be defined, tutorials to be made, etc).
3. Community can pick any topic from the struct and start the doc.
4. Community can suggest new topics to be added to the doc struct.

**Comment by JSeam2** [comment]
Gitbook should be free for open-sourced projects, but they do seem to be positioning more towards a commercial product. It might be better to go with open-sourced documentation that can be self-hosted. The site generated should be static and they can also be hosted within github.io. 

Some alternatives which are viable are
1. [Docusaurus](https://docusaurus.io/)
2. [Vuepress](https://vuepress.vuejs.org/)
3. [mkdocs material](https://squidfunk.github.io/mkdocs-material/)

**Comment by JSeam2** [comment]
Closed as [https://docs.ezkl.xyz](https://docs.ezkl.xyz) exists now
