### ISSUE TITLE
unnecessary qualification on `cargo build --release`

### ISSUE THREAD

**Issue by 0xhank** [zkonduit/ezkl#199]
![image](https://user-images.githubusercontent.com/71292860/233619944-86c36989-721e-4d9a-9532-22162fc0d883.png)

**Comment by alexander-camuto** [comment]
huh that's an interesting one. Can't reproduce it anywhere. Can you send your `cargo` version etc...

**Comment by 0xhank** [comment]
Rust version: rustc 1.71.0-nightly (8bdcc62cb 2023-04-20)
Cargo version: cargo 1.71.0-nightly (d0a4cbcee 2023-04-16)
Running on Windows 11 Pro 22H2

Removing the unused_qualifications lint flag resolved it...

**Comment by alexander-camuto** [comment]
interesting thanks -- I'll push a fix in a moment :)
