### ISSUE TITLE
Dynamic Lookup Tables

### ISSUE THREAD

**Issue by lancenonce** [zkonduit/ezkl#212]
Some operations, such as softmax, require variable-length lookup tables that are established at proving time. PSE's Halo2 fork already has support for dynamic lookup tables ([lookup_any](https://github.com/privacy-scaling-explorations/halo2/blob/b739b543d6f3d7d3a4ebb11660dd168136c4ae5f/halo2_proofs/src/plonk/circuit.rs#L1593)) which enable us to use Instance or Advice columns to use as lookup tables. We should incorporate this to provide an option for a dynamic lookup tables for current ops and future more complex ones.

**Comment by alexander-camuto** [comment]
(Note: duplicate of #100 so make sure to close both when done)

**Comment by lancenonce** [comment]
Closing for a future update
