### ISSUE TITLE
Ops to implement

### ISSUE THREAD

**Issue by jasonmorton** [zkonduit/ezkl#23]
- [x] Max
- [x] Max pooling
- [x] Average pooling (a specialization of conv)
- [ ] dynamic scaling, and special cases such as softmax

**Comment by alexander-camuto** [comment]
For `max` we might be able to leverage something from [here](https://eprint.iacr.org/2019/417.pdf). In particular this identity might be useful 
![unknown](https://user-images.githubusercontent.com/45801863/193322948-aae57bae-56b8-4a9c-9c15-d219765d2c77.png)
We can basically use the (scaled)-sigmoid as a comparison operator, using a (dynamic) lookup to perform max ops.

**Comment by Genysys** [comment]
Hey is this still relevant? Might need some pointers but would love to take it on

**Comment by jasonmorton** [comment]
Yes, still very much relevant!
