### ISSUE TITLE
Docs Fix: Example Models Link

### ISSUE THREAD

**Issue by OnlyOneJMJQ** [zkonduit/ezkl#232]
Hoping this is the right procedure. Checked out the repos and couldn't find one for the retype docs.

### Summary
The link to ONNX examples in the retype docs is broken, and it looked to me like the original repo it pointed to is gone and not integrated elsewhere (I could be wrong). [ONNX Model Zoo](https://github.com/onnx/models) could be a good candidate for replacement.

### Link Section of the Documentation
[Command Line Interface - python and cli tutorial 🐍](https://docs.ezkl.xyz/command_line_interface/): "For samples of onnx files see here."

**Comment by alexander-camuto** [comment]
Hey @OnlyOneJMJQ thanks for flagging. Onnx models were moved to this repo at `examples/onnx` :) 

@lancenonce can you fix the links in the docs

**Comment by lancenonce** [comment]
Yes, thanks for the flag @OnlyOneJMJQ !

**Comment by lancenonce** [comment]
Done with the 2nd most recent PR.

fixed issue #232
