### ISSUE TITLE
Example leveraging the wasm prover / verifier

### ISSUE THREAD

**Issue by alexander-camuto** [zkonduit/ezkl#243]
We currently have `wasm-32-unknown-unknown` verifiers and provers compiling and testing in headless chrome. Though (currently) undocumented it would be great to build toy apps / a tutorial  using these. 

If you need instructions on how to compile, fist install `wasm-pack` then run: 

``` bash
rustup target add wasm32-unknown-unknown
cargo install wasm-server-runner
# note you may need to add rust-src for your platform, for instance for linux: 
rustup component add rust-src --toolchain nightly-2022-11-03-x86_64-unknown-linux-gnu
# if you don't believe me that these things run correctly locally 
 wasm-pack test --chrome --headless -- -Z build-std="panic_abort,std"
```

The tutorial should prove / verify proofs directly in the browser

**Comment by lancenonce** [comment]
completed with: https://github.com/zkonduit/ezkl/pull/288 and ezkl-doc updates.
