### ISSUE TITLE
Create a repository of already deployed Verifier.sol so redeployment isn't needed

### ISSUE THREAD

**Issue by JSeam2** [zkonduit/ezkl#253]
### Is your proposal related to a problem?

Verifier.sol is a view function that smart contracts can reference onchain. If a Verifier.sol has been deployed onchain, another similar one does not need to be deployed. There should be a service that keeps track of this so that end users don't need to redeploy existing Verifiers.

### Describe the solution you'd like

Have a hardhat or foundry plugin that checks for Verifier.sol that have been deployed. If the bytecode of the local Verifier.sol matches with something already deployed onchain, inform a user of its existence, address, and chain where it is deployed. 

The user should then decide whether to point to that deployed contract in their implementation instead. As Verifier.sol is a view function it can be reused. 

A database of such deployments will have to be maintained unfortunately. Users who deploy Verifier.sol onchain could submit their contract into the database.

**Comment by ethan-crypto** [comment]
One potential solution, if we want to keep everything decentralized and avoid maintaining a database, is to implement a lightweight factory contract using [CREATE2](https://docs.openzeppelin.com/cli/2.8/deploying-with-create2). This factory contract would handle the deployment of all verifiers. Before deploying a new one, it could check for the existence of a verifier by hashing the runtime bytecode (potentially the creation code as well if we want to be on the safe side, but definitely not the [metadata](https://docs.soliditylang.org/en/v0.8.20/metadata.html)) of the verifier and cross-referencing it against a mapping (bytes=>address). This should provide us with a unique identifier to check whether a verifier has been deployed before. 

For better accessibility and visibility of the deployed verifiers, we should also create a [subgraph](https://thegraph.com/docs/en/developing/creating-a-subgraph/) for the verifier factory. This would allow for easy decentralized querying of verifiers deployed in production.
