### ISSUE TITLE
cargo build error (cannot locate remote-tracking branch 'origin/ac/send-sync-region')

### ISSUE THREAD

**Issue by ExcellentHH** [zkonduit/ezkl#280]
### Describe the bug
When I try to execute `cargo build --release` on the current version (bc5abf50a23bc00b95e133d380c5b0926a1528fd), the following error occurs:

```
warning: unused manifest key: target.wasm32-unknown-unknown.runner
    Blocking waiting for file lock on package cache
    Updating git repository `https://github.com/zkonduit/halo2`
error: failed to get `halo2_proofs` as a dependency of package `ezkl-lib v0.1.0`

Caused by:
  failed to load source for dependency `halo2_proofs`

Caused by:
  Unable to update https://github.com/zkonduit/halo2?branch=ac/send-sync-region

Caused by:
  failed to find branch `ac/send-sync-region`

Caused by:
  cannot locate remote-tracking branch 'origin/ac/send-sync-region'; class=Reference (4); code=NotFound (-3)
```
I have checked <https://github.com/zkonduit/halo2> and found that it has only one "main" branch, and there is no "ac/send-sync-region" branch.

I'm not sure whether the error occurred because of a wrong configuration of my environment or a wrong operation, so I'm looking for your help.

***Any insights are appreciated, thanks for the hard work!***

**Comment by alexander-camuto** [comment]
apologies -- branch should be restored now ! let me know if that works

**Comment by ExcellentHH** [comment]
> apologies -- branch should be restored now in #281 ! let me know if that works

Thank you for your prompt reply. The issue has been resolved and the program can now be compiled and run successfully!
