### ISSUE TITLE
Ubuntu SIGINT on conv2d_mnist example run 

### ISSUE THREAD

**Issue by zkbitcoin** [zkonduit/ezkl#30]
Running `target/release/examples/conv2d_mnist`
The first digit is a 5.0
VK took 204
PK took 125
Killed

trying now with rust version 1.66.0-nightly

a no go even with maxing out cores cargo run --release --example conv2d_mnist --jobs 8

**Comment by jasonmorton** [comment]
Thank you for posting the issue! 
I get the same result on Ubuntu when running out of memory, so this is expected (I tested it by forcing a memory limit).  Currently this example requires around 50GB of ram to run correctly. You might have luck by using a larger swap. 

We are certainly thinking about ways to get that memory usage down.

**Comment by zkbitcoin** [comment]
> Thank you for posting the issue! I get the same result on Ubuntu when running out of memory, so this is expected (I tested it by forcing a memory limit). Currently this example requires around 50GB of ram to run correctly. You might have luck by using a larger swap.
> 
> We are certainly thinking about ways to get that memory usage down.

sorry for late response, confirming on the RAM limit (machines does up to 30G)

**Comment by jasonmorton** [comment]
Serializing the intermediate computation would probably work, interesting idea!  This would require an upstream change in halo2, and would probably be a bit slow as you say. But it would enable the proof to at least run on more machines.   There are also a fair number of optimizations to do that will help get the memory down.

If we can understand the memory access pattern better, the disk version might not be too bad.

**Comment by jasonmorton** [comment]
I'm going to close this for now, but we can reference it if we get serialization working.
