### ISSUE TITLE
"RANGE" gate not satisfied

### ISSUE THREAD

**Issue by georgwiese** [zkonduit/ezkl#303]
### Describe the bug

When mock-proving with parameters output with `calibrate-settings`, I get a bunch of failing constraints, e.g.:

```
error: constraint not satisfied

  Cell layout in region 'model':
    | Offset | A1 | A2 |
    +--------+----+----+
    | 295519 | x0 | x1 | <--{ Gate 'RANGE' applied here

  Constraint '':
    ((S6 * (0x2 - S6)) * (0x3 - S6)) * (x0 - x1) = 0

  Assigned cell values:
    x0 = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593efff790c
    x1 = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593efffa722
```

### Expected behaviors

Not sure why this fails, at least I would need some instructions as to what to change.

Since it does work with other parameters, it also seems like `calibrate-settings` outputs invalid parameters.

### Steps to reproduce the bug

- I'm using [`lenet.onnx`](https://github.com/zkp-gravity/zkml-benchmark/blob/ba40a2988434a65c689f242600c3588dd84b9db9/models/lenet.onnx), and [`input.json`](https://github.com/zkp-gravity/zkml-benchmark/blob/ba40a2988434a65c689f242600c3588dd84b9db9/models/input.json), both generated with [this Python script](https://github.com/zkp-gravity/zkml-benchmark/blob/ba40a2988434a65c689f242600c3588dd84b9db9/zkml_benchmark/train_mnist.py)
- Run `ezkl calibrate-settings -M models/lenet.onnx -D models/input.json --settings-path settings.json`
- Run `ezkl mock -M models/lenet.onnx -D models/input.json --settings-path settings.json`

The generated `settings.json` is:
```json
{
    "run_args": {
        "tolerance": {
            "Abs": {
                "val": 0
            }
        },
        "scale": 5,
        "bits": 19,
        "logrows": 20,
        "batch_size": 1,
        "input_visibility": "Private",
        "output_visibility": "Public",
        "param_visibility": "Private",
        "pack_base": 1,
        "allocated_constraints": null
    },
    "num_constraints": 295510,
    "model_instance_shapes": [
        [
            1,
            10
        ]
    ],
    "num_hashes": 0,
    "required_lookups": [
        {
            "ReLU": {
                "scale": 32
            }
        }
    ],
    "check_mode": "SAFE"
}
```

The generated settings seem to contribute to the problem, because the following line works:
```
ezkl mock -M models/lenet.onnx -D models/input.json --scale 7 --bits 23 --logrows 24
```

### Device and Operating System

OS: Ubuntu
Version: 22.04.2 LTS
Processor: Intel ([Hetzner CX51](https://www.hetzner.com/cloud) instance)
Memory: 32 GB

### Additional Information

Used the (at the time of writing) most recent EZKL commit: 3dee1334c0b963db3797fd62aa78b269d808b308

**Comment by alexander-camuto** [comment]
Hey @georgwiese thank you for flagging this. Can you try the following:

1. `ezkl calibrate-settings -M models/lenet.onnx -D models/input.json --settings-path settings.json`
2. `ezkl forward -M models/lenet.onnx -D models/input.json --settings-path settings.json`
3. `ezkl mock -M models/lenet.onnx -D models/input.json --settings-path settings.json`

Let me know if that addresses your issue :)

**Comment by georgwiese** [comment]
Yes, it does! 🎉 

The difference is that the output values are changed, I assume because of quantization:

<img width="701" alt="Screenshot 2023-06-15 at 14 59 28" src="https://github.com/zkonduit/ezkl/assets/1701960/a320f573-b31b-4df0-8acd-91622e914713">

So I guess I should just integrate a forward pass into the pipeline? Or is it the purpose of the `--tolerance` parameter to allow for some deviation in the predictions?

**Comment by alexander-camuto** [comment]
Correctamundo. 

You can do either -- we're about to roll out tooling which allows you to a) track and b) compensate for quantization error :) If you join our telegram group (listed in readme) -- can notify you as soon at it is ready
