### ISSUE TITLE
Refactoring the `calibrate` method to be compatible with wasm32

### ISSUE THREAD

**Issue by sigridjineth** [zkonduit/ezkl#343]
### Is your proposal related to a problem?
Yes, our current codebase restricts the use of the calibrate function on the [execute.rs](https://github.com/zkonduit/ezkl/blob/4ffbd68d1c3dd08fe27749aebf30e82967919e22/src/execute.rs#L593) within the wasm32 environment. This limitation arises due to the conditional compilation attribute `#[cfg(not(target_arch = "wasm32"))]`, which explicitly excludes the function from being compiled for wasm32. I will post more about things after exploring the possibilities of refactoring the method codebase

### Describe the solution you'd like
I suggest we adapt the calibrate function to be wasm32 compatible. This adaptation could involve modifying or entirely removing the `#[cfg(not(target_arch = "wasm32"))]` attribute. However, doing so may necessitate further changes to ensure that the function and its dependencies align with the constraints of the WebAssembly environment.

### Describe alternatives you've considered
An alternative approach could be the creation of a wasm32 specific variant of the calibrate function, while preserving the existing version for other architectures. This approach, however, could lead to code duplication and potentially increase future maintenance efforts.

### Additional context
This proposal warrants a thorough examination of the calibrate function to determine if it employs features incompatible with wasm, such as direct file I/O or multi-threading. We should also ensure that any dependencies the function relies on are compatible with wasm.

If this issue takes so much time to explore, I will first address the issue (https://github.com/zkonduit/wasm-tutorial-web/issues/4) in the web-tutorial repository. We can generate via CLI and prepare a case for deploying onto a node.js server. This resolution should provide us with valuable insights for modifying the calibrate function to be wasm32 compatible.

Making the `calibrate` function compatible with wasm32 would enhance the flexibility of our codebase and widen its applicability across various environments including web browser environments.

**Comment by alexander-camuto** [comment]
closing as its beyond the current scope given the performance of wasm bindings. As mentioned the tutorial and the issue (https://github.com/zkonduit/wasm-tutorial-web/issues/4) should make the provenance of files more explicit
