### ISSUE TITLE
Integration tests for EVM hardforks to validate that deployment works for different hardforks

### ISSUE THREAD

**Issue by JSeam2** [zkonduit/ezkl#364]
### Is your proposal related to a problem?

The evm is constantly evolving and ezkl utilizes unique opcodes for the verifier contracts. As a result, it is not certain that the produced verifier will work on every single evm hardfork. 

### Describe the solution you'd like

As a sanity check and to improve reliability, it would be useful to check what evm hardforks are supported by the generated verifier code as part of the integration tests.

As anvil is being used, it possible to explicitly specify the hardfork being used. [See anvil options](https://book.getfoundry.sh/reference/anvil/#options). The hardfork used should be explicitly declared during tests.

### Additional Information

This is related to https://github.com/zkonduit/ezkl/issues/349

**Comment by glazec** [comment]
I am exploring potential solutions to this issue. One approach is to modify `tests/wasm/testBrowserEvmVerify.test.ts` so that the hardfork parameters are passed to localEVMVerify. These parameters can be obtained when the user specifies their desired fork via the CLI.

When I ran `npm run test`, I found I missed  KZG.sol to run the tests.
```
FAIL  tests/wasm/testBrowserEvmVerify.test.ts (15.519 s)
  ● localEVMVerify › should return true when verification succeeds
    ENOENT: no such file or directory, open '../ezkl/examples/onnx/1l_mlp/kzg.sol'
```

@alexander-camuto

**Comment by alexander-camuto** [comment]
@glazec the best entrypoint is with cargo test as it generates the required files

@ethan-crypto can you give instructions as to how to run the test with cargo for @glazec ?

**Comment by ethan-crypto** [comment]
@glazec You can run any of the cargo tests defined [here]:(https://github.com/zkonduit/ezkl/blob/main/tests/integration_tests.rs#L1000C1-L1094)

So for instance to run the `kzg_evm_prove_and_verify_` test you would run 
``` bash
cargo nextest run --release --verbose tests_evm::kzg_evm_kzg_params_prove_and_verify --test-threads 1
```
I think the best approach to this would be to spin up different anvil instances for each hardfork on different ports.

**Comment by glazec** [comment]
I've successfully set up the local environment and passed the tests. Now, I'm considering how to implement tests for different forks.

Question 1: There are approximately 15 hardforks supported by Anvil:

```
Frontier,
Homestead,
Dao,
Tangerine,
SpuriousDragon,
Byzantium,
Constantinople,
Petersburg,
Istanbul,
Muirglacier,
Berlin,
London,
ArrowGlacier,
GrayGlacier,
Paris,
Shanghai,
Latest,
```

Which of these should we prioritize for testing? Running tests on all hardforks could be time-consuming for CI/CD

Question 2: What is the intended scope of testing on different hardforks? Should all of the following tests be run on each hardfork?

yaml
Copy code
  - name: KZG prove and verify tests (EVM + kzg inputs)
        run: cargo nextest run --release --verbose tests_evm::kzg_evm_kzg_input_prove_and_verify --test-threads 1
  ...
  - name: KZG prove and verify tests (EVM + hashed outputs)
        run: cargo nextest run --release --verbose tests_evm::kzg_evm_hashed_output_prove_and_verify --test-threads 1

Question 3: Regarding the implementation, you mentioned running on different ports. I assume that different forks will run on different ports, and we will execute every integration test once for each fork. Let me know if you have any feedback on this method.

**Comment by glazec** [comment]
@alexander-camuto When trying to solve this, I encounter three questions mentioned above. Could you please help me on that?

**Comment by JSeam2** [comment]
@glazec 

1. We can prioritize Paris onwards. Which means that solidity `>= v0.8.18` would be the supported targets for now. This should make the library work for various optimistic L2s for the time being. There will be issues for older EVM versions unfortunately which could be an issue for L2s. This will be problematic for the Validium rollups/ZK rollups unfortunately as some of them are still on London (Linea) I believe, however, I think they might be doing some upgrades which may help support later EVM versions.
2. Yes, we should run all the evm test cases on the various hard forks. If you could parameterize the tests it would help with future maintenance.
3. Both methods seem viable to me, though I would be more keen on spinning up the anvil instances and deleting them after each test so you get a clean environment for each test.

**Comment by glazec** [comment]
I made a draft. Here is the approach. Let me know what you think and I can put hardfork test for the rest of the tests. @JSeam2 

Approach:
- Add a hardfork enum
- Add a hardfork parameter for start_anvil and each test function.
- Use macro to make sure test run on each hardfork. Currently, we run London, Paris and latest blockchain fork.

![image](https://github.com/zkonduit/ezkl/assets/22890026/4c42b4a3-a7a1-4885-bd40-c09449c33d5c)

**Comment by glazec** [comment]
We can close this issue
