### ISSUE TITLE
Documentation compiling the model out of date 

### ISSUE THREAD

**Issue by ImmanuelSegol** [zkonduit/ezkl#510]
https://docs.ezkl.xyz/command_line_interface/#compiling-the-model

When running this command from the tutorial I get this error:

<img width="869" alt="image" src="https://github.com/zkonduit/ezkl/assets/11227560/982a142b-d12f-4db8-93c0-d3e16ec824df">

I think the correct command is `ezkl compile-circuit -M network.onnx -S settings.json --compiled-circuit network.ezkl`

**Comment by jasonmorton** [comment]
Thank you so much, fixed at https://docs.ezkl.xyz/command_line_interface/
