### ISSUE TITLE
documentation creating the circuit out of date

### ISSUE THREAD

**Issue by ImmanuelSegol** [zkonduit/ezkl#511]
https://docs.ezkl.xyz/command_line_interface/#creating-the-circuit

running `ezkl setup -M network.ezkl --srs-path=kzg.srs --vk-path=vk.key --pk-path=pk.key --settings-path=settings.json`

i get 

```
error: unexpected argument '--settings-path' found

  tip: a similar argument exists: '--srs-path'

Usage: ezkl setup <--compiled-circuit <COMPILED_CIRCUIT>|--srs-path <SRS_PATH>|--vk-path <VK_PATH>|--pk-path <PK_PATH>|--witness <WITNESS>>

For more information, try '--help'.
```

**Comment by jasonmorton** [comment]
Thank you so much, fixed at https://docs.ezkl.xyz/command_line_interface/
