### ISSUE TITLE
aggregate tutorial commands out of date

### ISSUE THREAD

**Issue by ImmanuelSegol** [zkonduit/ezkl#512]
when following the [aggregate](https://docs.ezkl.xyz/about_ezkl/commands/#aggregate) tutorial. I get this error

```
error: unrecognized subcommand 'compile-model'

  tip: a similar subcommand exists: 'compile-circuit'

Usage: ezkl <COMMAND>

For more information, try '--help'.
```

**Comment by alexander-camuto** [comment]
thanks so much for highlighting these -- will update asap

**Comment by jasonmorton** [comment]
Should be correct now, thank you!
