### ISSUE TITLE
Install from source fails

### ISSUE THREAD

**Issue by field-worker** [zkonduit/ezkl#664]
### Describe the bug

Cloning the repo and executing `cargo install --force --path .` fails.
Building the executable in release mode is ok.

### Device and Operating System

OS: MacOS
Version: Sonoma 14.2
Processor: Apple M2
Memory: 16 GB

### Additional Information
A whole bunch of errors related to `revm`. E.g.:

```
error[E0615]: attempted to take value of method `original_value` on type `&mut StorageSlot`
   --> <directory>/registry/src/index.crates.io-6f17d22bba15001f/revm-3.3.0/src/journaled_state.rs:534:18
    |
534 |         Ok((slot.original_value, present, new, is_cold))
    |                  ^^^^^^^^^^^^^^ method, not a field
    |
help: use parentheses to call the method
    |
534 |         Ok((slot.original_value(), present, new, is_cold))
    |                                ++
```

As I wrote, there's a workaround by building with `cargo build --release --bin ezkl` :)

**Comment by field-worker** [comment]
It seems that `cargo install` ignores the lock file, unless `--locked` is specified (indeed with that option it works). I'd suggest updating the command in the "Installing" section of the docs to include this flag.

**Comment by alexander-camuto** [comment]
the readme includes the --locked flag
