### ISSUE TITLE
`--srs-path` argument missing from docs 

### ISSUE THREAD

**Issue by field-worker** [zkonduit/ezkl#665]
### Describe the bug

The e2e example in the Getting Started section of docs should say:
`ezkl get-srs -S settings.json --srs-path=kzg.srs`, else we later get a "failed to load srs at kzg.srs" error.

**Comment by field-worker** [comment]
or provide a default value of `kzg.srs` or sth when no `--srs-path` is provided.

**Comment by alexander-camuto** [comment]
no srs-path gets downloaded to $EZKL_REPO_PATH/srs and subsequent commands already load from this. we'll patch the e2e example though @ethan-crypto

**Comment by alexander-camuto** [comment]
> or provide a default value of `kzg.srs` or sth when no `--srs-path` is provided.

this already happens
