### ISSUE TITLE
Model table fails to print / failure parsing the model

### ISSUE THREAD

**Issue by mmagician** [zkonduit/ezkl#670]
### Describe the bug
Hi.

I was trying a bunch of models from Hugging Face and couldn't parse any of them with the `ezkl table` command. Maybe I was just unlucky in picking the models... here are a few that failed and their error messages. The 1st and 3rd seem related, it looks like there might be some files missing but I really can't tell.

1. https://huggingface.co/TaylorAI/gte-tiny/blob/main/onnx/model_quantized.onnx
```
[E] [2023-12-19 20:12:52, ezkl] - failed: Failed analyse for node #330 "/embeddings/Shape" Shape
Error: Failed analyse for node #330 "/embeddings/Shape" Shape

Caused by:
    0: Infering facts
    1: Applying rule outputs[0].datum_type == TDim
    2: Impossible to unify I64 with TDim.
```
2. https://huggingface.co/jinaai/jina-embeddings-v2-small-en/blob/main/model.onnx
```
[E] [2023-12-19 20:20:47, ezkl] - failed: could not get output shape for node
Error: "could not get output shape for node"
```
3. https://huggingface.co/Xenova/glpn-kitti/blob/main/onnx/model_quantized.onnx
```
[E] [2023-12-19 20:21:30, ezkl] - failed: Failed analyse for node #3260 "/glpn/encoder/Shape" Shape
Error: Failed analyse for node #3260 "/glpn/encoder/Shape" Shape

Caused by:
    0: Infering facts
    1: Applying rule outputs[0].datum_type == TDim
    2: Impossible to unify I64 with TDim.
```

Mildly related to #181.

### Expected behaviors
Some of the above models are quite large, so maybe generating the proof would be too costly, but I should at least be able to parse it to see what's inside.

### Steps to reproduce the bug

1. Download the model from one of the above links
2. Execute `ezkl table -M MODELNAME.onnx`

**Comment by mmagician** [comment]
Tagging @erhant, thanks for pointing me to some of these models on Hugging Face.

**Comment by alexander-camuto** [comment]
Ah I see -- these are issues with the tract library. Can you open this issue there -- you should be able to replicate the same errors by using 

`tract MODELNAME.onnx`

See here https://github.com/sonos/tract

**Comment by alexander-camuto** [comment]
Have opened an issue on tract for 1 & 3. https://github.com/sonos/tract/issues/1293 

Will address 2 as that is an ezkl specific error

**Comment by alexander-camuto** [comment]
#673 fixes 2. Once merged you the model should table with the following command (if building from main): 


```bash
RUST_LOG=debug cargo run --bin ezkl --release -- table -M model.onnx --variables sequence_length=1,batch_size=1
```

**Comment by alexander-camuto** [comment]
Fyi @mmagician the tract issues were just resolved. Will merge those into latest PR
