### ISSUE TITLE
`DimError` when generating the circuit settings

### ISSUE THREAD

**Issue by mmagician** [zkonduit/ezkl#677]
### Describe the bug
Related to model 2 from https://github.com/zkonduit/ezkl/issues/670.

I'm failing to generate the settings json with the following command:
`ezkl gen-settings -M network.onnx --variables sequence_length=1,batch_size=1`

Getting a `DimError`, though I am not able to see any further info on what the cause is.
With [this new PR](https://github.com/zkonduit/ezkl/pull/676) I get a little more info:
```
[E] [2023-12-30 18:49:16, ezkl::graph::model] - dimensionality error when manipulating a tensor: The current dimension 512 must be contained in the new shape [1, 1, 1] or be 1
[E] [2023-12-30 18:49:16, ezkl] - failed: General synthesis error
```
### Steps to reproduce the bug

1. Run ...
2. Execute ...

### Device and Operating System

OS: MacOS
Version: Ventura 13.3.1
Processor: Apple M1
Memory: 16 GB

**Comment by alexander-camuto** [comment]
@mmagician you need to add the variables `--variables sequence_length=1,batch_size=1` to the end of the command as noted in #670

**Comment by mmagician** [comment]
The command I ran actually includes that, sorry @alexander-camuto the original comment didn't mention the right command, edited now.
So the issue still stands.

**Comment by mmagician** [comment]
@alexander-camuto ping to re-open the issue as per the above comment.

**Comment by alexander-camuto** [comment]
reopened and patched @mmagician
