### ISSUE TITLE
Numerical accuracy report table not being shown in Jupyter environments after calibration

### ISSUE THREAD

**Issue by gufett0** [zkonduit/ezkl#693]
### Describe the bug
 Numerical accuracy report table not being shown in Jupyter environments after calibration

### Expected behaviors
 I
![2024-01-19 17 56 00](https://github.com/zkonduit/ezkl/assets/104091627/12935c74-00c3-45d7-8ae6-e89b18c538e1)

### Steps to reproduce the bug
 Run all the steps till 
res = ezkl.calibrate_settings(cal_path, model_path, settings_path, "accuracy")
just like in the demo notebook example

### Device and Operating System

OS: MacOS
Version: Monterey 12.7
Processor: 2,9 GHz Dual-Core Intel Core i5
Memory: 16 GB

**Comment by alexander-camuto** [comment]
small note that this works fine on ARM Macs. Suspicion is that this is an issue with Py03 on other architectures.

**Comment by alexander-camuto** [comment]
solved by latest release
