### ISSUE TITLE
Setup fails with invalid value

### ISSUE THREAD

**Issue by Gonmeso** [zkonduit/ezkl#721]
### Describe the bug
When performing the `setup` command it fails with the following error:

```python
Traceback (most recent call last):
  File "/Users/gonmeso/src/giza/platform-images/ezkl/r.py", line 19, in <module>
    ezkl.setup(
RuntimeError: Failed to run setup: invalid value: integer `2268737582`, expected variant index 0 <= i < 2
```

The following files have been used:

* Linear regression model
* Linear regression input
* kzg_6.srs for params

### Expected behaviors

The expected behaviour is the `setup` command to succeed and generate the proving and verify key.

### Steps to reproduce the bug

ezkl version: `8.3.0`

Model used can be found at: https://github.com/zkonduit/ezkl/tree/main/examples/onnx/linear_regression

Code to replicate:

```python
import ezkl

data_path = "input.json"
model_path = "network.onnx"
settings_path = "settings.json"
srs_path = "kzg_6.srs"
vk_path = "ezkl.vk"
pk_path = "ezkl.pk"
circuit_params = "circuit_params.json"

run_args = ezkl.PyRunArgs()
run_args.variables = [("batch_size", 1)]
res = ezkl.gen_settings(model_path, settings_path, py_run_args=run_args)
ezkl.calibrate_settings(
                data_path, model_path, settings_path, "resources", max_logrows = 20
            )
ezkl.setup(
    model_path,
    vk_path,
    pk_path,
    srs_path,
    circuit_params,
)
```

Full execution trace:

```
[00:00:00] ########################################      60/60      Calibration Done.                                                                                   

 <------------- Numerical Fidelity Report (input_scale: 13, param_scale: 13, scale_input_multiplier: 10) ------------->

+-----------------+-----------------+-----------------+-----------------+----------------+------------------+----------------+----------------+---------------------+--------------------+------------------------+
| mean_error      | median_error    | max_error       | min_error       | mean_abs_error | median_abs_error | max_abs_error  | min_abs_error  | mean_squared_error  | mean_percent_error | mean_abs_percent_error |
+-----------------+-----------------+-----------------+-----------------+----------------+------------------+----------------+----------------+---------------------+--------------------+------------------------+
| -0.000019073486 | -0.000019073486 | -0.000019073486 | -0.000019073486 | 0.000019073486 | 0.000019073486   | 0.000019073486 | 0.000019073486 | 0.00000000036379788 | -0.000004209112    | 0.000004209112         |
+-----------------+-----------------+-----------------+-----------------+----------------+------------------+----------------+----------------+---------------------+--------------------+------------------------+


Traceback (most recent call last):
  File "r.py", line 19, in <module>
    ezkl.setup(
RuntimeError: Failed to run setup: invalid value: integer `2268737582`, expected variant index 0 <= i < 2
```
### Device and Operating System

OS: MacOS
Version: 13.0
Processor: Apple M2
Memory: 16 GB

### Additional Information

Python: 3.11.3
Dependencies: `ezkl==8.3.0`
Rust Version: 1.75.0-nightly

**Comment by alexander-camuto** [comment]
@Gonmeso you need to run `compile_circuit` before `setup` :) you should see examples of this in all the notebooks :) and then pass the compiled model path to setup

**Comment by JSeam2** [comment]
Would it be better if we add some marker bytes on the compiled circuit? This way we can check if the model file is the right one and provide a more helpful error message would tell a user that they needed to compile the onnx file.

Without prior context a user wouldn’t have known that they needed to call `compile-circuit` given the error message provided

**Comment by alexander-camuto** [comment]
@JSeam2 lets create a seperate issue for this that details marker strats and close this one

**Comment by Gonmeso** [comment]
Maybe the documentation should be updated @alexander-camuto as it says the following on the [python bindings section](https://docs.ezkl.xyz/python_bindings/#setup):

```
model (required): A string representing the file path of the ONNX model to be processed and used to build the circuit.
```

**Comment by alexander-camuto** [comment]
@ethan-crypto when you have the time can you update the docs

**Comment by alexander-camuto** [comment]
@Gonmeso ty for flagging. We have auto-generated python docs coming up in #714
