### ISSUE TITLE
PanicException: the value of ``extended_k`` is bigger than the size of the field ``S`` after calibrating settings

### ISSUE THREAD

**Issue by CaixiangFan** [zkonduit/ezkl#741]
### Describe the bug

Halo2 proof system threw this PanicException in creating the circuits:
```
thread '<unnamed>' panicked at /root/.cargo/git/checkouts/halo2-049b997cf7195aea/4d7e6dd/halo2_proofs/src/poly/domain.rs:55:9:
extended_k (29, k=26, j=6) with degree (335544320) must be <= S (28), the size of the field
```
### Expected behaviors

The automatically calibrated settings should contain an ``extended_k`` <= ``S`` in running ``ezkl.setup(...)``.

### Steps to reproduce the bug

1. Clone [this repo](https://github.com/CaixiangFan/zkpet/tree/checkpoints).
2. Enter ``/src/electricity_centralized_ZKML.ipynb``. Define a model with 321 Linear modules like [this example](https://github.com/zkonduit/ezkl/tree/v9.5.0/examples/onnx/scatter_nd).
```Model(
  (Linear): ModuleList(
    (0-320): 321 x Linear(in_features=192, out_features=24, bias=True)
  )
) with 1486872 parameters
```
3. Execute "Define Files Path". Skip ``Converting Model to ONNX`` and ``Setting circuit parameters`` as ONNX and ``settings.json`` are provided.
[settings.json](https://github.com/zkonduit/ezkl/files/14594214/settings.json)
4. Execute ``Compiling the Model`` and ``Creating the circuit``.
The PanicException is expected here.

### Device and Operating System

OS: Ubuntu 
Version: 22.04
Processor: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
Memory: 16 GB

### Additional Information

Python: 3.11.8
EZKL: v9.5.0
Rust: 1.74.0-nightly

**Comment by alexander-camuto** [comment]
@CaixiangFan can you check #745 fixes your issue ?

**Comment by CaixiangFan** [comment]
> @CaixiangFan can you check #745 fixes your issue ?

Unfortunately, it does not fix the issue. The same problem still happens in my test with the updated EZKL.

**Comment by alexander-camuto** [comment]
confirmed that this was resolved on latest on main :)
