### ISSUE TITLE
Error on integration of ezkl with huggingface pretrained models

### ISSUE THREAD

**Issue by mammadmaheri7** [zkonduit/ezkl#751]
### Bug Description
I have generated a pre-trained DistilBERT model fine-tuned for the QQP task to the EZKL circuit. While ONNX generation proceeds without errors, encountering an issue with mocking. Specifically, the error pertains to a dynamic lookup table in a node, with approximately 180 IDs.

### Steps to Reproduce
1. Access the provided notebook that can be executed in Google Colab.
2. Execute all cells,  the cell containing `ezkl.mock` will result in the error.
Notebook Link: [Google Colab Notebook](https://drive.google.com/file/d/19jeC30k63iJeK4VmnpUrlMQNGxMuV2RV/view?usp=share_link)

onnx link: [link](https://drive.google.com/file/d/1_fHsS3WRYaA8BjOvBgfMRwrwm2Gqp2sD/view?usp=share_link)

Please note that running the notebook will generate the same onnx file.

### Device and Operating System Information
- OS: Ubuntu
- Version: 22.04
- Processor: Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz
- Memory: 64 GB

**Comment by alexander-camuto** [comment]
looks like you skipped calibrating -- likely causing your issues
