### ISSUE TITLE
error with 'create-evm-verifier'

### ISSUE THREAD

**Issue by G1aYue** [zkonduit/ezkl#757]
After i run the command
 `ezkl create-evm-verifier --srs-path=kzg.srs --vk-path vk.key --sol-code-path verif.sol --settings-path=settings.json`
there is an error

> xingc@ubuntu:~/Desktop/idolmodel$ ezkl create-evm-verifier --srs-path=kzg16.srs --vk-path vk.key --sol-code-path verif.sol --settings-path=settings.json
> [*] [2024-03-27 03:18:22, ezkl] - 
>  |  
>  |          ███████╗███████╗██╗  ██╗██╗
>  |          ██╔════╝╚══███╔╝██║ ██╔╝██║
>  |          █████╗    ███╔╝ █████╔╝ ██║
>  |          ██╔══╝   ███╔╝  ██╔═██╗ ██║
>  |          ███████╗███████╗██║  ██╗███████╗
>  |          ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝
>  |  
>  |          -----------------------------------------------------------
>  |          Easy Zero Knowledge for the Lyrical.
>  |          -----------------------------------------------------------
>  |  
>  |          
> [*] [2024-03-27 03:18:22, ezkl::execute] - checking solc installation..
> [*] [2024-03-27 03:18:23, ezkl::pfsys::srs] - loading srs from "kzg16.srs"
> [*] [2024-03-27 03:18:23, ezkl::execute] - downsizing params to 16 logrows
> [*] [2024-03-27 03:18:23, ezkl::pfsys] - loading verification key from "vk.key"
> [*] [2024-03-27 03:18:23, ezkl::pfsys] - done loading verification key ✅
> [E] [2024-03-27 03:18:23, ezkl] - failed: could not find contract
> Error: "could not find contract"

But it still generate the verif.sol,   and it does not generate the  verifier_abi.json
why ?

**Comment by alexander-camuto** [comment]
do you have solc installed ?

**Comment by G1aYue** [comment]
> do you have solc installed ?

yes， I have installed it
