### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by sirouk** [zkonduit/ezkl#783]
I'm working with an Altra Q80-30 chip and reached a dead-end with a project I'm working on as it requires ezkl but is not supported for ARM (aarch64).

I gave the binary install a shot and ended up with this:

ARM architectures are not supported for Linux at the moment. If you would need support for the ARM architectures on linux please submit an issue https://github.com/zkonduit/ezkl/issues/new/choose

Thanks in advance!

**Comment by alexander-camuto** [comment]
sounds good @JSeam2 or I will get on it

**Comment by alexander-camuto** [comment]
For now @sirouk you can build and install the repo from source on the machine: `cargo install --path . --locked`

**Comment by baonq-me** [comment]
I have the same problems, too. Did you use Equinix servers @sirouk ?

**Comment by alexander-camuto** [comment]
sounds like a different issue @baonq-me

**Comment by baonq-me** [comment]
> sounds like a different issue @baonq-me / that doesn't like like a valid path lol can you confirm that when you `ls` that path that the file exists ?

Yeah. After spending some time, I have successfully compiled and run ezkl 10.2.7 on Q80-30 using python binding. I think the issue can be closed.

**Comment by alexander-camuto** [comment]
awesome :) @baonq-me lmk if you have any other Qs
