### ISSUE TITLE
Failed to generate settings: [graph] [tract]

### ISSUE THREAD

**Issue by gufett0** [zkonduit/ezkl#816]
I tried to generate settings based on this onnx export, where 

`def resize_activations(activations, size):
    resized_activations = []
    for i in range(activations.size(1)):
        resized_activation = transforms.functional.resize(activations[:, i, :, :].unsqueeze(1), size).squeeze(1)
        resized_activations.append(resized_activation)
    return torch.stack(resized_activations, dim=1)`

`activations = mymodel.activations[0]`
`resized_activations = resize_activations(activations, (112, 112))`
`torch.onnx.export(
    mymodel,
    (img1, img2, resized_activations),
    model_path,
    export_params=True,
    opset_version=10,
    do_constant_folding=True,
    input_names=['img1', 'img2'],
    output_names=['cam'],
    dynamic_axes={'img1': {0: 'batch_size'}, 'img2': {0: 'batch_size'}, 'cam': {0: 'batch_size'}}
)`
    

and got 
<img width="567" alt="Screenshot 2024-06-18 at 12 17 12" src="https://github.com/zkonduit/ezkl/assets/104091627/f88a9950-a2de-4dc0-a23a-0e5247b53196">

To reproduce the behaviour you can find the class that extends nn.Module (you could use any pytorch neural network), the onnx file and test inputs here
[files.zip](https://github.com/user-attachments/files/15884533/files.zip)

### related issue
I also tried to use a different class with F.interpolate in it, but in that case opset_version >= 11 is required

**Comment by alexander-camuto** [comment]
sick ty for the issue. Will take a look

**Comment by alexander-camuto** [comment]
you can use opset >= 11 btw !

**Comment by jpomian** [comment]
I'm experiencing similar problem, although here it won't generate settings, because of some invalid operation. I'm using EZKL demo notebook for iris dataset. While it compiles model well and generates settings during setup phase. I can't get it to work locally.

Here is link to notebook that I'm using: https://colab.research.google.com/drive/1U4joKTra1FA4K9kWFSxLi15amwVu4Qow?usp=sharing

Here is error message:
```
RuntimeError: Traceback (most recent call last):
  File "/home/jpom/py/ezkl/ezkl-demo/iris2.py", line 192, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jpom/py/ezkl/ezkl-demo/iris2.py", line 144, in main
    res = ezkl.gen_settings(model_path, settings_path, py_run_args=py_run_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to generate settings: [graph] [tract] Failed analyse for node #7 "/fc1/MatMul" MatMulInference
```

Local python version: 3.12.2
Local pip version: 24.0

**Comment by alexander-camuto** [comment]
@gufett0 can you check if this problem occurs with latest on main ?

**Comment by alexander-camuto** [comment]
@gufett0 can't you provide a script that e2e generates the onnx. Rn I need to cobble a bunch of the above together and don't quite have the time to

**Comment by gufett0** [comment]
@alexander-camuto sorry for the late reply. 
I can confirm that the problem arises only for opset <= 12. 
You can find here a single notebook to reproduce e2e
[reproducible.zip](https://github.com/user-attachments/files/16347044/reproducible.zip)
