### ISSUE TITLE
PanicException: dynamic lookup or shuffle should only have one block

### ISSUE THREAD

**Issue by gufett0** [zkonduit/ezkl#819]
The model is not even that large, just over 100k params

You can find [here](https://colab.research.google.com/drive/1pP6jRD0gONq0CejEdKS4aZ4s9h2E3b-9?usp=sharing) the code to reproduce using with these weights[trained_NEWsnn_lr_0.1B.pth.zip](https://github.com/user-attachments/files/15904360/trained_NEWsnn_lr_0.1B.pth.zip)

<img width="785" alt="Screenshot 2024-06-19 at 19 35 04" src="https://github.com/zkonduit/ezkl/assets/104091627/85d57322-be02-4fa8-9d76-9a9592ca5a2e">

**Comment by alexander-camuto** [comment]
@JSeam2 @jasonmorton we need to patch the python docs
