### ISSUE TITLE
UnexpectedEof, message: "failed to fill whole buffer"

### ISSUE THREAD

**Issue by tensorajack** [zkonduit/ezkl#822]
### Steps to reproduce the bug

This error is found while running the model for the model used in the Omron Subnet. Previously you have mentioned just rolling back to v10.2.7 for the fix to this issue which does work. But I have gotten quite deep into the code, so it would be great to understand what is causing this issue so that I can fix it in the newer versions. 

Thank 

OS: MacOS
Version: Sonoma 14.4.1 
Processor: Apple M3
Memory: 8 GB

**Comment by alexander-camuto** [comment]
This isn't a bug. Serialization formats changed across major versions and we don't guarantee backwards compat across major bumps
